import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const AccordianContainer = () => {
  return (
    <div className='flex flex-row h-[40vh] w-full'>
        {/* Left */}
        <Accordion type="single" collapsible className="w-full flex md:flex-row flex-col items-center justify-between md:gap-16 h-full">
            {/* left */}
            <div className='md:w-1/2 w-full flex flex-col gap-4'>
                <AccordionItem value="item-1">
                    <AccordionTrigger className='accordian-item-heading'>Can I create videos in any niche?</AccordionTrigger>
                    <AccordionContent  className='accordian-item-content'>
                    Yes! You can create a video for nearly any topic or niche you want.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                    <AccordionTrigger className='accordian-item-heading'>What social media platforms do you support?</AccordionTrigger>
                    <AccordionContent className='accordian-item-content'>
                    We currently plan on supporting posting to Facebook, Instagram, TikTok and YouTube. We are working on adding support for other platforms.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                    <AccordionTrigger className='accordian-item-heading'>Are the videos unique?</AccordionTrigger>
                    <AccordionContent className='accordian-item-content'>
                    Yes! We create a new video each time using generative AI. This means that each video is unique and will not be the same as any other video. Even if two videos have the same topic, the script and images will be completely different.
                    </AccordionContent>
                </AccordionItem>
            </div>
            {/* Right */}
            <div className='md:w-1/2 w-full flex flex-col gap-4'>
                <AccordionItem value="item-4">
                    <AccordionTrigger className='accordian-item-heading'>Can I edit the videos?</AccordionTrigger>
                    <AccordionContent className='accordian-item-content'>
                    Yes, you can edit the video details such as the video's script, title, and background music.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-5">
                    <AccordionTrigger className='accordian-item-heading'>Do I own the videos?</AccordionTrigger>
                    <AccordionContent className='accordian-item-content'>
                    Yes, the videos are yours to do with as you please. You can download them and use them on other platforms, or even sell them to clients.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-6">
                    <AccordionTrigger className='accordian-item-heading'>Are there any types of content that are not allowed?</AccordionTrigger>
                    <AccordionContent className='accordian-item-content'>
                    While our generative AI models include an NSFW filter, we cannot guarantee that all content will be suitable for all audiences. Please be aware that we are not responsible for any content generated by our AI models.
                    </AccordionContent>
                </AccordionItem>
            </div>
        </Accordion>
    </div>
  )
}

export default AccordianContainer
